repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: "24.2.0"
    hooks:
      - id: black
        language_version: python3
        files: "^Python/"
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [
            "--in-place", # Make changes in place
            "--remove-all-unused-imports", # Remove unused imports
            "--remove-unused-variables", # Remove unused variables
          ]
  - repo: https://github.com/PyCQA/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--config=.flake8", "--max-line-length=150"]
        types: [python]
        additional_dependencies:
          - flake8>=3.7.8
          - flake8-black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  # # Ruff
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.2.2
  #   hooks:
  #     # Run the linter.
  #     - id: ruff
  #       types_or: [python, pyi, jupyter]
  #       args: [--fix]
  #     # Run the formatter.
  #     - id: ruff-format
  #       types_or: [python, pyi, jupyter]

    #Pylint
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "--max-line-length=150",
            "--disable=W1203,"
          ]

    # Yaml linters and formatters
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
